---
- hosts: "DLAPP,DLELAS"
  remote_user: ansible
  become: True
  roles:
    - common

# - hosts: "DLDB"
#   remote_user: infra
#   become: True
#   roles:
#     - dldb
#   vars:
#     ftpdbrealip: "10.148.0.26"

- hosts: "DLAPP"
  remote_user: ansible
  become: True
  roles:
    - dlapp
  vars:
    worker_process: 8
    predl_domain: pre-dl.dssvti.com

- hosts: "DLELAS"
  remote_user: ansible
  become: True
  roles:
    - dlelastic
  vars:
    elasticurl: https://test.dssvti.com:9200
    elastuser: elasticsearch
    elasticuser: elastic
    elasticpass: "Fn8rzGMzk14GIqdk3w03"
    tmpsuperuser: quangtd
    tmpsuperpass: quangtd@282!@2333
    testflag: true
