---
- name: Install nginx
  yum: name=nginx state=present
  register: nginxins

- name: Run rebuild Yum DB
  shell: rpm --rebuilddb && yum clean all
  when: nginxins.rc != 0

- name: Create SSL dir
  file: path=/etc/nginx/ssl state=directory

- name: Copy SSL Certs
  template: src='{{ item }}' dest=/etc/nginx/ssl/{{ item }}
  with_items:
    - ssl-dssvti.com-key
    - ssl-dssvti.com.pem

- name: Copy Nginx Main config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Create site enable dir
  file: path=/etc/nginx/site-enable state=directory

- name: Copy predl config
  template: src=ssl.dssvti.com.conf.j2 dest=/etc/nginx/site-enable/ssl.dssvti.com.conf
  notify: Restart nginx