---
- name: restart iptables
  service: name=iptables state=restarted

- name: refresh sysctl
  shell: sysctl -p

- name: Yum reload
  shell: yum clean all

- name: Restart Zabbix agent
  service: name=zabbix-agent state=restarted

- name: Restart SSHD
  service: name=sshd state=restarted